Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread     self.run()Thread-1
:
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
Exception in thread         pubsub.get_message(ignore_subscribe_messages=True,response = self.parse_response(block=False, timeout=timeout)Thread-1

:
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    if not block and not conn.can_read(timeout=timeout):    
response = self.parse_response(block=False, timeout=timeout)  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read

  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
fatal: No remote configured to list refs from.
/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
fatal: No remote configured to list refs from.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
      File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
        response = self.parse_response(block=False, timeout=timeout)response = self.parse_response(block=False, timeout=timeout)

  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)    
return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
redis.exceptions.ConnectionError: Connection closed by server.
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
fatal: No remote configured to list refs from.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/ashil/Hostel-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
